# Generated by Django 2.0.7 on 2018-07-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_userbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='status',
            field=models.CharField(choices=[('r', 'reading'), ('c', 'completed'), ('t', 'to read')], default='reading', max_length=1),
        ),
    ]
