# Generated by Django 2.0.7 on 2018-07-29 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180729_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='completed',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 29, 10, 23, 35, 379553, tzinfo=utc)),
        ),
    ]
