# Generated by Django 2.0.7 on 2018-07-29 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20180729_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='completed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
