# Generated by Django 2.0.7 on 2018-07-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20180729_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='status',
            field=models.CharField(choices=[('r', 'I am reading this book'), ('c', 'I have completed this book'), ('t', 'I want to read this book')], default='c', max_length=1),
        ),
    ]
