# Generated by Django 2.0.7 on 2018-07-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20180729_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='image',
        ),
    ]
