# Generated by Django 2.0.7 on 2018-07-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_badge_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booknote',
            old_name='note',
            new_name='description',
        ),
        migrations.AddField(
            model_name='booknote',
            name='type_note',
            field=models.CharField(choices=[('q', 'Quote'), ('n', 'Note')], default='q', max_length=1),
        ),
    ]
