# Generated by Django 2.0.7 on 2018-07-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20180729_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booknote',
            name='public',
        ),
        migrations.AddField(
            model_name='booknote',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
