# Generated by Django 2.0.7 on 2018-07-29 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20180729_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booknote',
            name='book',
        ),
        migrations.AddField(
            model_name='booknote',
            name='userbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.UserBook'),
        ),
    ]
