# Generated by Django 2.0.7 on 2020-10-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20181106_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='imagesize',
            field=models.CharField(max_length=2),
        ),
    ]
