# Generated by Django 3.1.2 on 2020-10-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_book_imagesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
