# Generated by Django 3.1.2 on 2020-12-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_userbook_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbook',
            options={'ordering': ['-favorite', '-completed', '-id']},
        ),
    ]
