# Generated by Django 3.1.12 on 2021-07-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        ('books', '0022_auto_20210703_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='booklists',
            field=models.ManyToManyField(related_name='booklists', to='lists.UserList'),
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
