# Generated by Django 3.2.5 on 2021-08-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_bookidconversion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookIdConversion',
            new_name='BookConversion',
        ),
    ]
