# Generated by Django 3.2.5 on 2021-08-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_rename_bookidconversion_bookconversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookconversion',
            name='googlebooks_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
