# Generated by Django 3.2.5 on 2021-08-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_alter_bookconversion_googlebooks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='term',
            field=models.TextField(),
        ),
    ]
