# Generated by Django 3.2.5 on 2021-08-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_alter_search_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.CharField(max_length=30),
        ),
    ]
