# Generated by Django 3.2.5 on 2021-08-22 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_importedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedbook',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
