# Generated by Django 3.2.5 on 2021-08-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0032_bookconversion_inserted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='importedbook',
            name='title',
            field=models.TextField(),
        ),
    ]
