# Generated by Django 3.2.13 on 2022-05-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_auto_20220528_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'searches'},
        ),
        migrations.AlterField(
            model_name='book',
            name='bookid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
