# Generated by Django 2.0.7 on 2019-06-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
