# Generated by Django 3.1.12 on 2021-07-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlist',
            options={'ordering': ['-inserted']},
        ),
    ]
