# Generated by Django 3.1.12 on 2021-07-03 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20210703_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlist',
            options={'ordering': ['name']},
        ),
    ]
