# Generated by Django 3.1.12 on 2021-07-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20210703_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
